### ISSUE TITLE
After installation of crc extension and its initialization using openshift preset  there are two openshift local endpoints

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#104]
I have install the crc-extension with latest tag into podman desktop 0.15.0. I have then went through the installation process for crc which ended up well, using openshift preset - it downloaded the crc bundle. I could see on the dashboard option to start Openshift local. I tried it, it complains about hyperv no enabled (expected), but the I switched to the settings->Resources and there are two endpoints for openshift local. 

![crc-extension-doubled](https://github.com/crc-org/crc-extension/assets/19164299/b865a752-cc4e-4731-a7b8-954b3fe2636f)

**Comment by gbraad** [comment]
@odockal can you check if by accident you run two instance of the extension?

**Comment by gbraad** [comment]
@jsliacan @anjannath do you see this too? Try to replay this on Windows as the system used to report it.

**Comment by adrianriobo** [comment]
I am seeing this on windows 11 with PD [v0.0.202305091513-52a0047](https://github.com/containers/podman-desktop/releases/tag/v0.0.202305091513-52a0047) (Fresh installation, ensure only installed crc extension once)

Just installed crc extension and select the microshift preset (it downloaded and extracted the bundle) now I see both OCP and microshift in there (I clicked on the OCP one)

![image](https://github.com/crc-org/crc-extension/assets/1957899/983a0683-5c2d-4eac-aebc-7b2b46868c43)

**Comment by adrianriobo** [comment]
what I think I saw is once I installed the extension the first cluster resource for Openshift Local was already there...then when I went through the crc installation and selected the preset the second one appeared

**Comment by evidolob** [comment]
This could happen, and should be fixed with https://github.com/crc-org/crc-extension/pull/98
