### ISSUE TITLE
Odd behaviour with 'Create new' after an instance exists

### ISSUE THREAD

**Issue by deboer-tim** [crc-org/crc-extension#122]
If I have a running OpenShift Local instance, the `Create new` button is still enabled, and leads to a screen where I can stop the running instance but nothing else. Supporting only one instance at a time is fine, but then the button should probably be disabled or removed after creating the first one.

I'm aware this could mean there's a feature requirement on Podman Desktop, but opening here since this is where the issue surfaces and would need to make a change either way.

**Comment by evidolob** [comment]
We could remove connection factory object when we have one, this will remove `Create new` button.
