### ISSUE TITLE
versions are not synched between OCI image tag and package.json version

### ISSUE THREAD

**Issue by benoitf** [crc-org/crc-extension#136]
If I pull the image `quay.io/redhat-developer/openshift-local-extension:v1.0.2`

package.json contains `version": "1.0.1"` while tag of the image is `v1.0.2`

so Podman Desktop might prompt user to update to v1.0.2 but this is already what we have, but it's then listed as 1.0.1

**Comment by gbraad** [comment]
https://github.com/crc-org/crc-extension/blob/f975968de77c148687b4165332c7e2d244b0ff73/package.json#L6

**Comment by gbraad** [comment]
@benoitf I will publish a new version v1.0.3 instead: #137

**Comment by anjannath** [comment]
fixed via #137

**Comment by gbraad** [comment]
@benoitf please have a look at: https://github.com/crc-org/crc-extension/releases/tag/v1.0.3

Synced as: [quay.io/redhat-developer/openshift-local-extension:v1.0.3](http://quay.io/redhat-developer/openshift-local-extension:v1.0.3)

Thanks for the report... :facepalm:
