### ISSUE TITLE
(undefined) message displayed on the dashboard

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#149]
<img width="1162" alt="Capture d’écran 2023-06-06 à 16 08 24" src="https://github.com/crc-org/crc-extension/assets/1636769/e7fe07ac-0a87-4be5-bdee-ea7f1f4bec18">

Not sure what it means in this context, but it is certainly disturbing in term of ux

**Comment by gbraad** [comment]
It should show the preset value. So this somehow was returned from the settings or current status as 'undefined'.  From the image it seems created (stopped), but not started.
