### ISSUE TITLE
[Bug]: Changing the kube context between crc and other provider (kind) via Podman Desktop triggers unwanted start of the OS local cluster

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#153]
Env: Red Hat OpenShift Local (user) v1.0.3, Podman Desktop 1.1.0, Fedora 37 and Windows 10 Pro.
I had this strange behavior happening when testing openshift local. 
I have installed os local, started the openshift preset. Deployed the app, tested. I have also installed another providers like kind and dev sandbox, thus I have multiple kube context available. 
I have stopped the openshift local. Switched between contexts and returned back to `crc-admin`, which triggered os local start up. 

![crc-autostart-bug](https://github.com/crc-org/crc-extension/assets/19164299/67bfcb45-2304-4d5d-b65c-8bd92bb83cd1)

**Comment by jeffmaury** [comment]
Closing as it was a Podman Desktop issue in the dashboard fixed then
