### ISSUE TITLE
Telemetry should include preset

### ISSUE THREAD

**Issue by deboer-tim** [crc-org/crc-extension#155]
The telemetry events for start, stop, commands do not include which preset is used. It would be good to log whether MicroShift or OpenShift Local is being used so we can prioritize between the two or understand when (e.g.) a behaviour or error is prevalent in one vs the other.

**Comment by deboer-tim** [comment]
Yes, no real need to record it twice, but it is usually easier when the data is in whichever relevant event you want to filter by. e.g. start is likely one we'd want to compare the profiles (or whether users behaviour is different for the profiles, e.g. do they start/stop one on demand vs leave the other running? how long do users typical run it?), so I'd include it in there even if there was an init/creation event that already included it.

The key thing we wanted to know is 'how much are people using MicroShift or OpenShift within Podman Desktop'. Unless the backend knows what triggered the action, the only place to get this would be via the Podman Desktop telemetry. Even if the extension has no real need to know IMHO it's worth one extra backend call to include this in telemetry/logs.

**Comment by gbraad** [comment]
The migration from Woopra to Amplitude might have dropped it from a view. I
have asked Praveen to update the Amplitude views last week as we have the
data.

-- 

   Gerard Braad | http://gbraad.nl

   STEM is the source, but BUILD is how you develop!
   [ Better Understanding Involves Learning and Doing ]

**Comment by gbraad** [comment]
> how much are people using MicroShift or OpenShift within Podman Desktop'

Every call records the originator for our backend telemetry
