### ISSUE TITLE
[Question] How do I switch the preset on windows/macOS from OpenShift to Microshift after Openshift was initiazlied and started

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#156]
I am not really sure how do I achieve above mentioned on windows using Podman Desktop. I do not want to make assumption but I tried a couple of option in order to achieve the change in preset via podman desktop and start microshift after openshift was started before but it was not obvious to me. Just changing of the preset in preferences does not really seems to work.

**Comment by gbraad** [comment]
It will request you to 'delete' the current installation, before you can start as the other preset.
This migh be slow(er) to process, as the preset change will trigger an API call and then inform the UI about this. The last part of that is not something we can control.

You should see the following:
https://github.com/crc-org/crc-extension/pull/131#issuecomment-1560457531

**Comment by gbraad** [comment]
I assume this has been answered
