### ISSUE TITLE
[Docs] describe how to install and use the extension

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-extension#16]
@themr0c, this is something we have to start outlining.
Especially in light of: https://github.com/containers/podman-desktop/pull/1686#issuecomment-1467668085

**Comment by gbraad** [comment]
We updated the website/project README

**Comment by themr0c** [comment]
Note: related pull request in Podman Desktop docs: https://github.com/containers/podman-desktop/pull/2486
