### ISSUE TITLE
Add description in the resource page when there is no OpenShift Local instances

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#164]
When there is no instances, the resource pages shows:

![image](https://github.com/crc-org/crc-extension/assets/695993/be62ab80-81c6-48a1-ac98-9b4b850c2ef4)

The provider API now has a field called: emptyConnectionMarkdownDescription

Proposed text (extracted from https://developers.redhat.com/products/openshift-local/overview)

Red Hat OpenShift Local is the quickest way to get started building OpenShift clusters. OpenShift Local is designed for local development and testing on an OpenShift cluster.

**Comment by slemeur** [comment]
Proposed empty connection description is fine for me
