### ISSUE TITLE
Notification shown after sucessful push to local cluster is very hard to notice

### ISSUE THREAD

**Issue by dgolovin** [crc-org/crc-extension#185]
On macOS notification is not visible right away and to see it I have to go to tray and click on date to see that image push was successful. On fedora it seems not showing up at all (it could be notification permission not set in settings).  Other extensions are using window.showInformationMessage which shows modal message dialog inside podman window. Would be good to use this simple approach across all push commands.

https://github.com/crc-org/crc-extension/blob/caccc05c969e75cfdebe7beef3ba6559021eeaca/src/image-handler.ts#L71

This issues is related to https://github.com/containers/podman-desktop/issues/3538.

**Comment by gbraad** [comment]
We have discussed this before, and this should be part of the 'tasks'. they will then end up in a trackable list and shiw progress and completion consistently. Unfortunately, we are not aware if this functionality is now available/finalized.

**Comment by gbraad** [comment]
I believe this is called now the 'Bell icon' list? https://github.com/containers/podman-desktop/issues/4406

**Comment by dgolovin** [comment]
Tasks are good solution to show progress, but there is no any visual information on that bell when task(s) finished. 

I agree that showing modal dialog is not ideal, but it is better that show something that is not easy to notice. There should be some sort of non blocking notification, but we don't have it right now.

**Comment by dgolovin** [comment]
> I believe this is called now the 'Bell icon' list? https://github.com/containers/podman-desktop/issues/4406

Correct.

**Comment by gbraad** [comment]
> don't have it right now

hence we delivered with the current Notifications. We hoped this would be available soon-ish. Notifications are very dependent on the OS and can, especially in the case of macOS be hidden (never show up), and in the case of Linux not be properly supported. If the other extensions use the modal form, this might work as a workaround... but this has t o be temporary. Modal dialogs should only be reserved for blocking tasks like a setup.

**Comment by dgolovin** [comment]
I agree crc-extension should show informaton message for now as temp solution. Implementation for information message at some point will be done in a form non blocking message dialog, the same way as tasks view shows tasks.

**Comment by gbraad** [comment]
Follow-up issue is filed here: https://github.com/crc-org/crc-extension/issues/191
