### ISSUE TITLE
[BUG] Impossible to reinstall the extension

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#197]
### General information

Because of #195 I've tried to delete the extension and wanted to reinstall it - unfortunately, I can't re-install it

<img width="1645" alt="Screenshot 2023-12-15 at 13 42 15" src="https://github.com/crc-org/crc-extension/assets/1636769/e4c1ce61-cdcc-4652-b48f-db5221fdef19">

  * OS: mac OS
  * Podman Desktop 1.7.0

## CRC version
```bash
# Put `crc version` output here
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by lstocchi** [comment]
@slemeur i tried it on Windows and Mac and it seems to work fine. Could you please re-try? Most probably it has already been fixed.
