### ISSUE TITLE
Simplify setup and pull secret flow with Red Hat SSO extension

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#200]
## Goals

Thanks to the work done on the Red Hat SSO extension, we now would like to automate the process of getting the pull secret to start openshift local. 

### Sub-tasks

- [x] #201
- [x] #207

**Comment by gbraad** [comment]
@dgolovin @jeffmaury

**Comment by dgolovin** [comment]
Implemented and merged to main.
