### ISSUE TITLE
[BUG] User gets blocked at the step of setting up OpenShift Local

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#202]
### General information

<img width="1162" alt="Screenshot 2024-03-01 at 15 16 20" src="https://github.com/crc-org/crc-extension/assets/1636769/b0f8e2f3-7bf9-48c4-b8d0-e8fe11cc1b5b">

How is the user supposed to move forward?

  * OS: macOS 
  * Hypervisor: KVM / Hyper-V / hyperkit / vfkit
  * Did you run `crc setup` before starting it (Yes/No)?
  * Running CRC on: Laptop / Baremetal-Server / VM

## CRC version
```bash
CRC version: 2.33.0+c43b17
OpenShift version: 4.14.12
Podman version: 4.4.4
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by slemeur** [comment]
This is the state you have, when:
- you create a microshift environment from podman desktop
- you delete it from crc cli

**Comment by gbraad** [comment]
> you delete it from crc cli

Does the same occur when you delete from Podman Desktop?

**Comment by slemeur** [comment]
<img width="1088" alt="Screenshot 2024-03-01 at 15 45 19" src="https://github.com/crc-org/crc-extension/assets/1636769/6455c3d7-2c3b-43a7-b631-e681c4f7dc64">
Can't create a cluster at the moment

**Comment by slemeur** [comment]
after upgrading from podman desktop:
slemeur@slemeur1-mac ~ % crc start
The executable version (2.33.0) doesn't match the daemon version (2.31.0)

**Comment by dgolovin** [comment]
Fixed as part of https://github.com/crc-org/crc-extension/issues/229.
