### ISSUE TITLE
Improve the UX create an environment

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#203]
## Goal
This screen gets really strange, you get there from Resources > Create New.
<img width="1162" alt="Screenshot 2024-03-01 at 15 21 38" src="https://github.com/crc-org/crc-extension/assets/1636769/9c9b302a-aac1-4e5f-b510-f3ddebde908f">

It is missing information and guidance to the end user on how to configure and set up the environment.
We should be consistent with the way we are doing for Podman.

<img width="1162" alt="Screenshot 2024-03-01 at 15 23 40" src="https://github.com/crc-org/crc-extension/assets/1636769/14fc3cf6-c10b-40f0-859f-9a26f732c9cb">

Also, the settings are all available to configure OpenShift local instance, but this is in another place than what we do for all other providers.
<img width="1162" alt="Screenshot 2024-03-01 at 15 24 42" src="https://github.com/crc-org/crc-extension/assets/1636769/e5a34d71-fcdd-47ef-91ed-e367c815cba4">

**Comment by lstocchi** [comment]
fixed by https://github.com/crc-org/crc-extension/pull/228
