### ISSUE TITLE
Allow to configure cpus, memory, disk size and pull-secret file location when creating new cluster

### ISSUE THREAD

**Issue by dgolovin** [crc-org/crc-extension#215]
Form to create OpenShift Local cluser is empty right now. Would be good to have:
1. Makrdown property with short explanation where those configuration values coming from with link to open extension settings and external documentation
2. Cpus, memory, disk size and optional pull-secret file location fields initialized by default from extension settings

![image](https://github.com/crc-org/crc-extension/assets/620330/c335f999-cd81-4b73-9c5f-28961f58259b)

### Additional context

```
  -c, --cpus int                  Number of CPU cores to allocate to the instance (default 2)
  -d, --disk-size uint            Total size in GiB of the disk used by the instance (default 31)
  -m, --memory int                MiB of memory to allocate to the instance (default 4096)
  -p, --pull-secret-file string   File path of image pull secret (download from https://console.redhat.com/openshift/create/local)
```

**Comment by gbraad** [comment]
> Form to create OpenShift Local cluser is empty right now

As we prioritize `crc config set` over any other way to provide the settings. Take note, any parameter for `crc start` is not a guarantee to work from the extension, as the extension relies on the use of the API endpoint: 

https://github.com/crc-org/crc/blob/813c80a473046247eb232bb7e9e3da79a954118b/pkg/crc/api/handlers.go#L119-L134

**Comment by lstocchi** [comment]
Closing. It was fixed by https://github.com/crc-org/crc-extension/pull/228
