### ISSUE TITLE
Create a CRC machine leads to empty page no link to return to Resources

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#221]
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
CRC version: 2.36.0+27c493
OpenShift version: 4.15.12
Podman version: 4.4.4
```
  
## CRC status
```bash
CRC VM:          Running
MicroShift:      Running (v4.15.12)
RAM Usage:       1.514GB of 3.828GB
Disk Usage:      5.626GB of 16.1GB (Inside the CRC VM)
Cache Usage:     7.22GB
Cache Directory: C:\Users\Jeff\.crc\cache
```

## CRC config
```bash
# Put `crc config view` output here
```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
```

### Steps to reproduce

  1. 
  2. 
  3. 
  4. 

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by dgolovin** [comment]
Similar to #187.
