### ISSUE TITLE
[BUG] Extension initialization failed: command 'crc.dev.terminal' already exists

### ISSUE THREAD

**Issue by odockal** [crc-org/crc-extension#250]
### General information

This happens when I tried to `initialize and start` the downloaded and configured OpenShift Local from PD dashboard.

### OS, versions, etc.
Mac OS 14
Podman Desktop 1.12.0
Crc-extention: latest tag used to install extension as of creation date of this issue (https://github.com/crc-org/crc-extension/pkgs/container/crc-extension/251283995?tag=latest)

Situation:
1. Have 1.3.0 extension installed
2.  Stop and uninstalled the extesion
3. Do a full clean up (delete crc cluster, delete crc binary, remove `.crc`)
4. Install crc-extension from nightly/latest
5. Install CRC from Dashboard
6. Assert: CRC was installed, pick up preset (microshift)
7. Initialize and start from Dashboard -> choose preset again!
8. Wait for crc to download bundle
9. Assert: Can start crc microshift
Actual result: `Extension initialization failed: command 'crc.dev.terminal' already exists`

**Comment by dgolovin** [comment]
I still can replicate it. The commands registration is tied to tray menu item creation and and that can happen multiple times. It leads to the same command is trying to register multiple times.

**Comment by dgolovin** [comment]
Cannot replicate it with #252 fixed. There are other usecases when state for OpenShift local is messed up, but that is when I use cli to cleanup OpenShift Local cluster.

**Comment by dgolovin** [comment]
@jeffmaury @odockal  could you install it from git hub nigntly repo and try to replicate?

**Comment by jeffmaury** [comment]
I can reproduce with commit dc5dc53b7502f0b258db596b1aa4c49bdb2c6318 but not with latest main so closing
