### ISSUE TITLE
Problem with defaults and minimums in package.json

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-extension#32]
The defaults and presets are currently part of `package.json` 
https://github.com/crc-org/crc-extension/blob/3427cc1526d10bd5d4b4a2d77b9ed8e30e0d99c9/package.json#L27

but this would cause problems, as these values are based on the preset that is chosen.

**Comment by evidolob** [comment]
We don’t have possibility to dynamically change `minimum` and `default` values. 
We could delete them defaults and minimums, default values doesn’t make sense now, as we have synchronisation of preferences, and we overwrite with crc one on extension start.
And I can add post edit validation, ie validate preference after user change.

**Comment by gbraad** [comment]
> I can add post edit validation, ie validate preference after user change.

This would make more sense
