### ISSUE TITLE
[BUG] "Error: {"Properties":null}" appears when trying to create a new OpenShift Local instance

### ISSUE THREAD

**Issue by danivilla9** [crc-org/crc-extension#324]
### General information

  * OS: Linux Fedora 40
  * Did you run `crc setup` before starting it? Yes
  * Running CRC on: Laptop

## CRC version
```bash
WARN A new version (2.41.0) has been published on https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/crc/2.41.0/crc-linux-amd64.tar.xz 
CRC version: 2.37.1+36d451
OpenShift version: 4.15.14
```
  
## CRC status
```bash
DEBU CRC version: 2.37.1+36d451                   
DEBU OpenShift version: 4.15.14                   
DEBU Running 'crc status'                         
CRC VM:          Stopped
OpenShift:       Stopped (v4.15.14)
RAM Usage:       0B of 0B
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     26.83GB
Cache Directory: /home/[username]/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1. Go to Dashboard on Podman Desktop
  2. Click on 'Initialize and start' button from the OpenShift Local section
  3. Wait for it to get to 'RUNNING' state
  4. Go to Resources->OpenShift Local, click on "Create new..." button
  5. Click on 'Create' button

### Expected
Either the button from step 4 should not be enabled or a new instance is created. Also the buttons to Start/Restart/Stop/Delete should be available on the Resources tab, as an instance already exists

### Actual
Error "Error: {"Properties":null}" pops up

### Video Evidence
[bug crc-extension create new instance.webm](https://github.com/user-attachments/assets/09857743-922c-4375-a3f7-4c4de73c23a8)

**Comment by jeffmaury** [comment]
Which version of the extension as you should see parameters now when creating the machine

**Comment by jeffmaury** [comment]
Closing it as it's not valid on 1.12.0+
