### ISSUE TITLE
Add Telemetry functionality

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-extension#34]
The original tray handled the telemetry gathering for the UI-related actions. If Podman Desktop can return if consent has been given, we can use this functionality to allow this to prevent an additional consent prompt.

Note: the backend already knows where actions originate from, so the telemetry in that case is redundant.

**Comment by gbraad** [comment]
? https://github.com/containers/podman-desktop/issues/1455

**Comment by gbraad** [comment]
I am looking at this

**Comment by benoitf** [comment]
> All we need is a consent indication: https://github.com/containers/podman-desktop/issues/1455 could provide this?

>telemetry.enabled

you'll get `env.isTelemetryEnabled` and `env.onDidChangeTelemetryEnabled` to be notified if user is changing the value
once https://github.com/containers/podman-desktop/pull/1996 is merged
