### ISSUE TITLE
Pull-secret dialog alternative

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-extension#56]
We need to come up with a solution to more clearly indicate the location to get the pull-secret, as the palette option is hard to understand; not very visible and provides no information on the next step to solve this.

While we have:
  * https://github.com/containers/podman-desktop/issues/1920
  * https://github.com/containers/podman-desktop/issues/1992

It is not clear when this will be available.

**Comment by gbraad** [comment]
We might be able to add a temporary dialog inside the `askAndStorePullSecret` function:

```
  extensionApi.window.showInformationMessage(`To pull container images from the registry, a pull secret is necessary.
  You can get a pull secret from the Red Hat OpenShift Local download page.
  Use the "Copy pull secret" option and paste the content.
  
  https://cloud.redhat.com/openshift/create/local`);
```

Two issues here, it is shown before the actual step where it is necessary, which is not ideal though still better than the current situation.
But second, this does not allow the link to be highlighted and clicked on.

@evidolob what are your thoughts on this?

**Comment by slemeur** [comment]
Yes, we should provide a quick fix for this until we have a better solution to handle the modal dialog in the API of podman-desktop extensions.
Suggestion from @gbraad is nice!

**Comment by slemeur** [comment]
Could we have that message in the placeholder being displayed both in the command palette and in the preferences?

**Comment by gbraad** [comment]
We have also added a clear 'Obtain Pull-secret' on the dashboard, right under the initialize button. 

Will see how much we can fit in the Preferences.

**Comment by slemeur** [comment]
thanks @gbraad !

**Comment by gbraad** [comment]
Ideally, this would have been a single dialog;

![image](https://github.com/crc-org/crc-extension/assets/1894/4835408c-5f27-4e56-994e-d1d3a5bbd47a)
