### ISSUE TITLE
Create Resource view for crc extention to have all the controls

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc-extension#58]
This is tracking issue for having the same controls like kind/podman resources have.

![Screenshot 2023-04-26 at 3 58 50 PM](https://user-images.githubusercontent.com/410007/234564584-b5705363-f037-4d4d-92b2-dbd090e19ac0.png)

**Comment by gbraad** [comment]
This should be resolved. Please verify @praveenkumar

**Comment by gbraad** [comment]
@evidolob It seems some recently created issues all do not show the Resource view. Either they haven't updated or still something not as expected?
