### ISSUE TITLE
Add Push Image to Openshift local cluster as option for image

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#61]
As of now we have option Push Image to kind cluster which works with kind cluster. We also need an option for Push Image to Openshift local cluster which sync image from podman machine instance to openshift Local instance.

Moved from https://github.com/containers/podman-desktop/issues/2263

**Comment by gbraad** [comment]
I miss feedback that the task started (ongoing) and finished. Is this also the case for Kind?
