### ISSUE TITLE
Initialize OpenShift Local does not lead to start

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#64]
I had the following configuration:

- CRC installed on my machine
- daemon was not running

I choose Initiliaze only, it started the daemon but when I got to the Resource page it is still empty

![crc](https://user-images.githubusercontent.com/695993/235179607-cdeb658f-5978-4aab-bb58-c7d792ae8c45.gif)

**Comment by gbraad** [comment]
The latest version of the extension has the Resource page buttons, so upgrading to the latest extension please?

And also, can you show what the console outputs?

**Comment by jeffmaury** [comment]
> The latest version of the extension has the Resource page buttons, so upgrading to the latest extension please?
> 
> And also, can you show what the console outputs?

This is based on the main branch

**Comment by jeffmaury** [comment]
I tried to run it again, got it reproduced but don't see anything special in the logs:

![image](https://user-images.githubusercontent.com/695993/235314418-b820a917-9e9e-4e7d-b06b-16b9c1527187.png)
