### ISSUE TITLE
Open Dev Terminal is not Windows friendly 

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#65]
Seems to initialize using sh/bash command:

![image](https://user-images.githubusercontent.com/695993/235189148-7fd11fec-d0fd-4a2e-9884-0a4fc86e2b13.png)

**Comment by gbraad** [comment]
According to my limited French understanding I see it does not understand `export`. This should however not be part of the `oc-env` command...

Can you provide more information abput your environment and perhaps in a Windows-Terminal PowerShell session run `crc oc-env` to see what the output is that is given to execute.

**Comment by jeffmaury** [comment]
So I was running my debug session from a bash shell in Windows which gives:

```
$ crc oc-env
export PATH="C:\Users\Jeff\.crc\bin\oc:$PATH"
# Run this command to configure your shell:
# eval $(crc oc-env)
```

The same in PowerShell:

PS C:\Users\Jeff\apps\crc\2.17.0> crc oc-env
$Env:PATH = "C:\Users\Jeff\.crc\bin\oc;$Env:PATH"
# Run this command to configure your shell:
# & crc oc-env | Invoke-Expression
PS C:\Users\Jeff\apps\crc\2.17.0>

**Comment by gbraad** [comment]
so the command reports what is expected.
however, in the session spawned it identifies as bash...
looks like a terminal configuration issue. can you share your config?
note: unable to reproduce


-- 

   Gerard Braad | http://gbraad.nl

   STEM is the source, but BUILD is how you develop!
   [ Better Understanding Involves Learning and Doing ]

**Comment by gbraad** [comment]
@jsliacan or @anjannath can you have a look at this to repro?

**Comment by anjannath** [comment]
@jeffmaury I think this only occurs when the user launches the `podman-desktop` app itself from a `bash` shell ? like run `yarn desk:run` from the bash/cygwin shell

so to reproduce i first installed Podman desktop using the MSI then installed the crc-extension -> started the microshift preset -> click on "Open developer console" and it launched powershell with the required `oc` env variables set

[2023-05-04-13-15-24.webm](https://user-images.githubusercontent.com/8885742/236143370-82744a90-7604-4ae9-ac79-b11596d6476c.webm)

**Comment by gbraad** [comment]
@jeffmaury was bash used to start Podman desktop?

**Comment by jeffmaury** [comment]
> @jeffmaury was bash used to start Podman desktop?

git-bash to be exact

**Comment by gbraad** [comment]
When PD is 'installed' on Windows, isn't the application started from the Start Menu instead?
