### ISSUE TITLE
Handle existing podman preset

### ISSUE THREAD

**Issue by deboer-tim** [crc-org/crc-extension#67]
Yes, we want to focus on hosting OpenShift and Microshift. But if you happen to have crc installed and used the podman preset, the extension is unable to do anything; trying to initialize hangs indefinitely. You are essentially stuck in this situation until you use the cli to delete and reset the config preset: https://access.redhat.com/discussions/6895111?tour=8

We should do the minimum to notify or help the user out of this situation. Ideally the other actions in the UI would be disabled and there'd be a warning with an optional action to fix the situation; even a warning with a link to a doc would be ok.

**Comment by gbraad** [comment]
Instead, we can detect the preset and suggest that the extension currently only works for OpenShift-based presets and allow the user to ignore or switch. WDYT?

**Comment by evidolob** [comment]
We could do, detect that user has `podman` preset configured, notify user that currently extension supports only `openshift` and `mikroshift` presets, then ask to change preset, with existing UI.

Or we could add statusbar item, which indicate which preset is used, and `podman` will have an error icon, click on that item will lead to change preset.

@gbraad WDYT?

**Comment by gbraad** [comment]
I will refer the second... less intrusive

**Comment by gbraad-admin** [comment]
I'll have a look what we can do...

**Comment by gbraad** [comment]
![image](https://github.com/crc-org/crc-extension/assets/1894/4f46aa24-7647-412e-abc1-be4175a6311e)

**Comment by deboer-tim** [comment]
+1 to a warning like this, but 'preferences' is still a bit vague. I'd include the full path, i.e. "Settings > Preferences > Red Hat OpenShift Local > Preset".
