### ISSUE TITLE
nit: Improve extension description

### ISSUE THREAD

**Issue by deboer-tim** [crc-org/crc-extension#68]
The current extension description is a bit wordy:
`"This extension provides a Red Hat OpenShift Local cluster and allows Podman Desktop to interact with it"`
and stands out from the other extensions. It should probably be something more like:
`"Integration for OpenShift Local"`
or at least start with that and include a short description of what OpenShift Local is or what you can do with it.

**Comment by gbraad** [comment]
fixed in #96
