### ISSUE TITLE
Resource still exists after deleting it

### ISSUE THREAD

**Issue by deboer-tim** [crc-org/crc-extension#72]
I now see the OpenShift Local instance under Settings > Resources (yay!). I clicked on the delete button and get a notification that is has been deleted, but it is still there. I can delete a second time and get an error that it doesn't exist and I can click start (?) to create it.

Expectation: Clicking delete makes it disappear, and then I need to create a new instance before I can see (and start) it again.

**Comment by evidolob** [comment]
The problem is that crc has no create command, for crc there are no difference between vm is stopped or deleted.
So it is impossible to create crc vm, to create vm we need to start it.

@gbraad  We could add 'create' function for PD, which internally just start the crc. WDYT?

**Comment by evidolob** [comment]
@gbraad I think we can, extension is able to detect when no VM(cluster) exist.
I just varied that 'create' just start crc, which user might not expect.

**Comment by gbraad** [comment]
If the extension needs a different set of states, I am very OK with
that. As long as they match with the expectation between both.
And perhaps, revision might be necessary. Ask Jakub for his state
transition document. I did a while back, but didn't receive it.

On Wed, May 3, 2023 at 9:27 PM Yevhen Vydolob ***@***.***> wrote:
>
> @gbraad I think we can, extension is able to detect when no VM(cluster) exist.
> I just varied that 'create' just start crc, which user might not expect.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 

   Gerard Braad | http://gbraad.nl

   STEM is the source, but BUILD is how you develop!
   [ Better Understanding Involves Learning and Doing ]

**Comment by deboer-tim** [comment]
It won't be fixed until PR #98 is merged.

**Comment by gbraad** [comment]
unfortunately I can't merge that PR yet. some serious layout issues caused by PD. more info in the PR.
