### ISSUE TITLE
[Todo] modify text when choosing the preset 

### ISSUE THREAD

**Issue by jeffmaury** [crc-org/crc-extension#74]
When a preset is to be chosen, the labels are microshift and openshift, they should be MicroShift and OpenShift

![image](https://user-images.githubusercontent.com/695993/235967021-da1d51a7-458b-49bc-9c44-a1c49b529480.png)

**Comment by jeffmaury** [comment]
Please also note the text seems truncated as it ends by ....

**Comment by gbraad** [comment]
no final texts have been decided on as this dialog is not according to
design (missing functionality). just a placeholder for now.

**Comment by gbraad** [comment]
https://github.com/crc-org/crc-extension/blob/dcf5f11e64c6acf1095248a18337668d6cf86c07/src/crc-setup.ts#L40-L41

**Comment by gbraad** [comment]
Awaiting the markdown option to allow to 'style' the current selection dialog. @cdrage says this is possible, but has not been exposed as part of the API. Related to: https://github.com/containers/podman-desktop/issues/1920

**Comment by slemeur** [comment]
Ok so for the time being, let's use:
- Title: Red Hat OpenShift Local Preset
- Description:
`Which preset bundle would you like to use with OpenShift Local. Microshift (experimental), provides a lightweight and optimized environment with a limited set of services. OpenShift, provides a single node OpenShift cluster with a fuller set of services, including a web console (requires more resources).`
- Buttons
  - Left: "MircroShift (experimental)"
  - Right: "OpenShift"
  
  
Is that possible?

**Comment by gbraad** [comment]
Will do... Awaiting @cdrage's response on #1920

**Comment by gbraad** [comment]
![image](https://github.com/crc-org/crc-extension/assets/1894/b55af39e-abb1-42fd-bc04-c927b9d2b647)

**Comment by slemeur** [comment]
Sounds good to me for the time being
