### ISSUE TITLE
Preset change doesn't reset the defaults of cpu/memory

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc-extension#76]
By default we have openshift preset enabled with default mem/cpu. But if a user want to use `microshift` preset then it doesn't change the defaults `cpu/memory` in the extension side and have it same.
<img width="1026" alt="Screenshot 2023-05-04 at 12 24 09 PM" src="https://user-images.githubusercontent.com/410007/236131727-ae0e231c-374a-471b-bade-ccb5104159e0.png">

**Comment by gbraad** [comment]
There is something most likely missing. The backend enforces the new defaults, and on rereading this would return the correct values. I think therefore an update might be missing.
