### ISSUE TITLE
Provide indication onto where to get the pull secret

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#80]
We need to provide an indication to the end user onto where to get the pull secret, otherwise, most users will be just stuck

**Comment by gbraad** [comment]
we are currently documenting this, and creating a video.

  * #16 

Ideally this should be implemented as in the design, or according to the alternative approach. all are currently not possible:

  * https://github.com/containers/podman-desktop/issues/1920
  * https://github.com/containers/podman-desktop/issues/1992
  * #56

**Comment by gbraad** [comment]
Closing as issues around this request already exist and are in progress
