### ISSUE TITLE
Doing "esc" when asked to provide the pull secret does not restore to previous state

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#82]
From the dashboard:
![cancel-run-OpenShiftLocal](https://user-images.githubusercontent.com/1636769/236243776-39219d6a-184e-418f-b2fa-22a8e43efe25.gif)

From the resources:
![cancel-installation of OpenShiftLocal](https://user-images.githubusercontent.com/1636769/236244156-cb161c37-3111-4c0f-9653-0e15698fb5d2.gif)

**Comment by gbraad** [comment]
This is most likely inconsistent behavior from PD as it does not draw focus to the input. This is why we prefer to have an actual modal dialog as per design.

**Comment by gbraad** [comment]
This feels like another shortcoming in the dasbboard, which also relates to the #81. There is no way to actively refresh/update the dashboard for it's content. So this is all based on the state of `detectionChecks`.
