### ISSUE TITLE
Button to open the OpenShift CRC config file

### ISSUE THREAD

**Issue by slemeur** [crc-org/crc-extension#84]
From the settings, it would be nice to be able to add a button that opens the config file of CRC.

<img width="1573" alt="Capture d’écran 2023-05-04 à 16 57 15" src="https://user-images.githubusercontent.com/1636769/236247016-c3bd7c1f-b750-4a9c-8a0d-8eef4abd901d.png">

**Comment by gbraad** [comment]
While this is json, we never exposes the file for editing. All interaction happens with:

```
$ crc config
```

as some values are not inside the config file, such as the pull-secret.

**Comment by slemeur** [comment]
hum, since this is happening locally and the pull secret is mine (and accessible from the settings), I don't think this is an issue.
Otherwise, it would be about displaying all values from the config.json.

Context:
- I was discussing with a user who previously had installed and configured CRC; At that time, he configured the proxy setting, but when he tried to use the extension, an error was raised, mentioning a proxy. it took time before we figured out that it was from CRC configuration itself.

**Comment by gbraad** [comment]
> it took time before we figured out that it was from CRC configuration itself.

We have CRC specific configuration options to set the proxy and no-proxy, but they are overwritten for Linux/macOS users when invoked from a commandline with these set as environment variables. It might be related to Windows where we do not pick these settings up from the configuration screen.

> the pull secret is mine (and accessible from the settings)

not really. only when you specify a file... but when you copy-paste one, thsi is stored in the system's specific security store.

All the values that are stored in the case of Microshift are as follows:
```json
{
  "consent-telemetry": "yes",
  "preset": "microshift"
}
```
Note: default values are suppressed and not stored by `crc config`, so this is not intuitive to use outside of the API and `crc config` command.

**Comment by gbraad** [comment]
We will first try to have the background daemon observe (watch) the configuration file for modifcations, and implement the logstream to which the extension can subscribe. As We ideally want to close the loop when the user changes the file and we find validation errors... as it would allow us to provide feedback through a UI (the extension is not directly responsible for the config contents).

**Comment by gbraad** [comment]
This will be more complicated when we implement the config files for each preset. Closing as 'wontfix'.
