### ISSUE TITLE
Incorrect naming of OpenShift Local in the preferences

### ISSUE THREAD

**Issue by gbraad** [crc-org/crc-extension#85]
In the image I notice the incorrect formatting of the name again: `Openshift-Local`, which should be `OpenShift-Local`.

![](https://user-images.githubusercontent.com/1636769/236247016-c3bd7c1f-b750-4a9c-8a0d-8eef4abd901d.png)

**Comment by gbraad** [comment]
@evidolob Can you confirm this is not something we can control, right?

**Comment by gbraad** [comment]
Ideally this should be handled as a 

```json
"displayname": "OpenShift Local"
```

**Comment by gbraad** [comment]
Created an upstream issue for PD: https://github.com/containers/podman-desktop/issues/2358

**Comment by evidolob** [comment]
We already provide https://github.com/crc-org/crc-extension/blob/main/package.json#L21-L22 label for configuration, but podman-desktop ignore it.

**Comment by evidolob** [comment]
And we have ` "displayName": "Red Hat OpenShift Local",` in our [package.json](https://github.com/crc-org/crc-extension/blob/main/package.json#L3)

**Comment by jeffmaury** [comment]
Closing as 1.2.0 shows:

![image](https://github.com/crc-org/crc-extension/assets/695993/b214ffa8-cfda-4d8e-8aff-b658597f09ce)
