### ISSUE TITLE
Hang in the `Starting` stage 

### ISSUE THREAD

**Issue by praveenkumar** [crc-org/crc-extension#89]
- Install extension from current master
- No cluster exist on the system
- Go to the preference an selected preset as microshift
- Now want to start the cluster

It hangs `Starting` stage until manually refresh and also that is not even starting the cluster (no crc start process when click to start)

<img width="1037" alt="Screenshot 2023-05-08 at 11 23 31 AM" src="https://user-images.githubusercontent.com/410007/236744736-69f7b224-ec5e-48f0-a677-d7de1bc18e46.png">

The dev console print following as soon as I hit `Run Openshift Local`
```
dex.ts:1299 main ↪️ [openshift-local] Error: cluster is busy

    at DaemonCommander.start (/Users/prkumar/.local/share/containers/podman-desktop/plugins/ghcriocrcorgcrcextension/dist/extension.js:9335:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startCrc (/Users/prkumar/.local/share/containers/podman-desktop/plugins/ghcriocrcorgcrcextension/dist/extension.js:25250:24)
    at async Ij.startProviderLifecycle (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:83:47731)
    at async /Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:335:2063
    at async node:electron/js2c/browser_init:2:97945
```

**Comment by gbraad** [comment]
Unable to repro

![image](https://github.com/crc-org/crc-extension/assets/1894/dfe59891-a3d2-4a81-99e3-1ea6299a89a5)

**Comment by gbraad** [comment]
@praveenkumar when does the API (`start`) send the reply `cluster is busy` ?

**Comment by evidolob** [comment]
`cluster is busy` it is response from daemon
Look like daemon is hanging for some reason.

**Comment by gbraad** [comment]
When we encounter a `500` we might want to show this error state more clearly. But this is definitely not something that we can control/expect.

Was this on the M1, @praveenkumar ?

**Comment by praveenkumar** [comment]
I tried it again on M1 and not able to produce it, may be because of daemon on crc side which caused it. Going to close it and will debug more  if again faced.

**Comment by gbraad** [comment]
We need to test the daemon on M1 more rigorous; it seems to suffer from stability issues.
